name: "Bug report 🐛"
description: Report errors or unexpected behavior
title: "Bug: "
labels:
  - bug

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Before submitting, please make sure to search through existing issues.
      options:
        - label: I have searched the existing issues!
          required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: Please share with us the step(s) required to reproduce the bug.
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Message
      description: If possible, please share the error message that you received.
      placeholder: Error Messages
      render: JSON
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If possible, please include screenshots and paste them into the markdown editor below.
      placeholder: Screenshots
    validations:
      required: false

  - type: markdown
    attributes:
      value: "Thanks for completing the bugh report!"
